name: 'Walrus Sites Provenance'
description: 'Securely deploy Walrus Sites with verifiable SLSA provenance and tamper-proof signatures.'
author: 'zktx.io'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  config-path:
    description: 'Path to site config JSON file'
    required: false
    default: './site.config.json'

env:
  ED25519_PRIVATE_KEY:
    description: 'Private key in Sui format (starts with "suiprivkey")'
    required: true

runs:
  using: 'node20'
  main: 'dist/deploy/index.js'
