export const MAX_BLOB_SIZE = 5 * 1024 * 1024; // 5MB
export const MAX_BLOB_REGISTRATIONS_PER_TX = 100;
export const MAX_BLOB_CLEANUPS_PER_TX = 100;
export const BLOB_OBJECT_LOOKUP_CONCURRENCY = 10;
export const SITE_PTB_COMMAND_BUDGET = 850;
export const SITE_PTB_BYTE_BUDGET = 120_000;
